name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: Checks (Node ${{matrix.node_version}})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 24
          - lts/*

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node_version}}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm clean-install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage

      - name: Integration tests
        run: npm run test:integration:coverage

      - name: Build
        run: npm run build
